"""
MCPC Core Law: Physics Domain Interface Definition Specification (IDS)
----------------------------------------------------------------------
This file defines the physical measurement data hierarchy. 
It strictly separates universal measurement traits from L2-specific assumptions.
"""

# =============================================================================
# [ABSTRACT / MCPC UNIVERSAL]
# Base class for all physical measurements. 
# This core structure will persist across all MCPC Levels (L1-L4).
# =============================================================================

from dataclasses import dataclass
import numpy as np
from enum import Enum, auto

class PhysicalConstants:
    G = 6.67430e-11          # Gravitational constant (m^3 kg^-1 s^-2)
    C = 299792458.0          # Speed of light (m/s)
    AU = 149597870700.0      # Astronomical Unit (m)

class ComponentHealthStatus(Enum):
    NOMINAL = auto()
    DEGRADED = auto()
    FAILED = auto()

@dataclass
class PhysicalMeasurementBase:
    """
    Root class for any data generated by a physical sensor.
    Ensures that every measurement is tied to a specific simulation epoch.
    """
    phys_timestamp: float    # True simulation time of the measurement event


# =============================================================================
# [L2-SPECIFIC / POINT MASS APPROXIMATION]
# Microwave-based Inter-Satellite Link (ISL) measurement.
# This assumes the spacecraft is a point mass and the sensor provides 
# relative spherical coordinates (Range, Azimuth, Elevation).
# =============================================================================
@dataclass
class MicrowaveISLMeasurement(PhysicalMeasurementBase):
    """
    L2-Specific Implementation: RF/Microwave-based relative measurement.
    Used for formation acquisition and maintenance at the point-mass level.
    """
    range_m: float           # Measured relative distance (m)
    azimuth_rad: float       # Measured azimuth angle (rad)
    elevation_rad: float     # Measured elevation angle (rad)
    signal_strength: float   # Normalized signal power [0.0 to 1.0]
    
    # [NOTE] In L3/L4, this may be replaced by specific Sensor Models 
    # (e.g., LiDAR, Vision) which will inherit from PhysicalMeasurementBase.
